name       : gmmlib
version    : 18.4.1
release    : 11
source     :
    - https://github.com/intel/gmmlib/archive/intel-gmmlib-18.4.1.tar.gz : 7970a8ae4e16efb98f38fbbc0346eea03227fc4462a9bd8e8077277cc3430a84
license    : MIT
component  : programming.library
summary    : Intel(R) Graphics Memory Management Library
description: |
    Intel(R) Graphics Memory Management Library
libsplit   : no
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    # Intel apparently opted to not invest in a proper build system.
    pushd solusBuildDir
    install -D -d -m 00755 $installdir/%libdir%/
    install -m 00644 Source/GmmLib/*.a $installdir/%libdir%/.
    install -m 00644 Source/GmmLib/*.so $installdir/%libdir%/.

    popd
    install -D -d -m 00755 $installdir/usr/include/{common,umKmInc}
    install -m 00644 Source/inc/common/*.h $installdir/usr/include/common/.
    install -m 00644 Source/inc/umKmInc/*.h $installdir/usr/include/umKmInc/.
