name       : gmmlib
version    : 20.4.1
release    : 12
source     :
    - https://github.com/intel/gmmlib/archive/intel-gmmlib-20.4.1.tar.gz : d54d547f9f9e74196dead6a338923039ea10c859f1f693f33f10be1562b81d6d
license    : MIT
component  : programming.library
homepage   : https://github.com/intel/gmmlib/
summary    : Intel(R) Graphics Memory Management Library
description: |
    The Intel(R) Graphics Memory Management Library provides device specific and buffer management for the Intel(R) Graphics Compute Runtime for OpenCL(TM) and the Intel(R) Media Driver for VAAPI.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove empty dirs in include
    find $installdir/usr/include/igdgmm/GmmLib -type d -empty -delete
