name       : gmmlib
version    : 0.0.0
release    : 10
source     :
    - git|https://github.com/intel/gmmlib.git : a5015343bc932e39747c57ea5dec0cbf28685465
license    : MIT
component  : programming.library
summary    : Intel(R) Graphics Memory Management Library
description: |
    Intel(R) Graphics Memory Management Library
libsplit   : no
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    # Intel apparently opted to not invest in a proper build system.
    pushd solusBuildDir
    install -D -d -m 00755 $installdir/%libdir%/
    install -m 00644 Source/GmmLib/*.a $installdir/%libdir%/.
    install -m 00644 Source/GmmLib/*.so $installdir/%libdir%/.

    popd
    install -D -d -m 00755 $installdir/usr/include/{common,umKmInc}
    install -m 00644 Source/inc/common/*.h $installdir/usr/include/common/.
    install -m 00644 Source/inc/umKmInc/*.h $installdir/usr/include/umKmInc/.
