name       : gmmlib
version    : 22.1.5
release    : 16
source     :
    - https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-22.1.5.tar.gz : b429cdff2c236274f2b9a32ac4ac2ed5d1655d3c87c557fe0fb7de6b6c906f18
license    : MIT
component  : programming.library
homepage   : https://github.com/intel/gmmlib/
summary    : Intel(R) Graphics Memory Management Library
description: |
    The Intel(R) Graphics Memory Management Library provides device specific and buffer management for the Intel(R) Graphics Compute Runtime for OpenCL(TM) and the Intel(R) Media Driver for VAAPI.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove empty dirs in include
    find $installdir/usr/include/igdgmm/GmmLib -type d -empty -delete
