name       : gmmlib
version    : 22.3.3
release    : 17
source     :
    - https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-22.3.3.tar.gz : 86651bd2803c9f0afd82471bec784e65d2b418dee315a053d22215eb2a679be7
license    : MIT
component  : programming.library
homepage   : https://github.com/intel/gmmlib/
summary    : Intel(R) Graphics Memory Management Library
description: |
    The Intel(R) Graphics Memory Management Library provides device specific and buffer management for the Intel(R) Graphics Compute Runtime for OpenCL(TM) and the Intel(R) Media Driver for VAAPI.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove empty dirs in include
    find $installdir/usr/include/igdgmm/GmmLib -type d -empty -delete
